import {
  ArrowDown,
  ArrowUp,
  AudioLines,
  Brush,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Copy,
  Download,
  Ellipsis,
  Eraser,
  Eye,
  EyeOff,
  FilePlus,
  FolderOpen,
  Ghost,
  Hand,
  House,
  Layers,
  Lock,
  LockOpen,
  Maximize,
  Minus,
  Music,
  PaintBucket,
  Palette,
  Pause,
  Pipette,
  Play,
  Plus,
  Redo2,
  Repeat,
  Settings,
  Share2,
  Smartphone,
  SquarePlus,
  StepBack,
  StepForward,
  Trash2,
  Undo2,
  Upload,
  X,
  ZoomIn,
  ZoomOut,
  createElement,
} from 'lucide';

export const icons = {
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  audio: AudioLines,
  brush: Brush,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  help: CircleHelp,
  copy: Copy,
  download: Download,
  more: Ellipsis,
  eraser: Eraser,
  eye: Eye,
  eyeOff: EyeOff,
  filePlus: FilePlus,
  open: FolderOpen,
  onion: Ghost,
  hand: Hand,
  home: House,
  layers: Layers,
  lock: Lock,
  unlock: LockOpen,
  fit: Maximize,
  minus: Minus,
  music: Music,
  fill: PaintBucket,
  palette: Palette,
  pause: Pause,
  eyedropper: Pipette,
  play: Play,
  plus: Plus,
  redo: Redo2,
  loop: Repeat,
  settings: Settings,
  share: Share2,
  install: Smartphone,
  newFrame: SquarePlus,
  prev: StepBack,
  next: StepForward,
  trash: Trash2,
  undo: Undo2,
  upload: Upload,
  close: X,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
};

export type IconName = keyof typeof icons;

export function icon(name: IconName, size = 20): SVGElement {
  const el = createElement(icons[name], { width: size, height: size, 'aria-hidden': 'true' });
  el.classList.add('icon');
  return el;
}
